# Generated by Django 5.0.6 on 2024-11-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_product_type_product_inventory_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tipo_ventidible',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
