# Generated by Django 5.0.6 on 2024-09-14 22:10

import django.db.models.deletion
import documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoImportante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_documento', models.CharField(max_length=100)),
                ('archivo', models.FileField(storage=documentos.models.MediaStorage(), upload_to=documentos.models.custom_filename_document)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('funeraria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.funeraria')),
            ],
        ),
    ]
