# Generated by Django 5.0.6 on 2024-11-03 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0018_alter_contrato_fecha_fin_velatorio_and_more'),
        ('velatorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservasala',
            name='contrato',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserva', to='contratos.contrato'),
        ),
    ]
