# Generated by Django 5.0.6 on 2024-11-03 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_funeraria_tyc'),
        ('velatorios', '0002_reservasala_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservasala',
            name='funeraria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='accounts.funeraria'),
            preserve_default=False,
        ),
    ]
