# Generated by Django 5.0.6 on 2024-11-07 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velatorios', '0003_reservasala_funeraria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salavelatorio',
            name='encargado',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_worker': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salas_encargado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salavelatorio',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
