# Generated by Django 5.0.6 on 2024-11-17 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_funeraria_tyc'),
        ('contratos', '0018_alter_contrato_fecha_fin_velatorio_and_more'),
        ('velatorios', '0004_salavelatorio_encargado_salavelatorio_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condolencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fallecido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condolencias', to='contratos.fallecido')),
                ('funeraria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condolencias', to='accounts.funeraria')),
                ('reserva_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condolencias', to='velatorios.reservasala')),
            ],
        ),
    ]
