# Generated by Django 5.0.6 on 2024-08-27 00:57

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(max_length=16, unique=True)),
                ('phone', models.CharField(blank=True, default='Sin número', max_length=14, null=True)),
                ('username', models.CharField(default='default_username', max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_worker', models.BooleanField(default=False)),
                ('contacto_telefono', models.CharField(blank=True, max_length=14, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=255, null=True)),
                ('sueldo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prevision', models.CharField(blank=True, max_length=100, null=True)),
                ('sistema_salud', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('funcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Funeraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, default='Sin número', max_length=14, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, storage=accounts.models.MediaStorage(), upload_to=accounts.models.custom_filename_funerarias)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funeraria_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='funeraria_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='accounts.funeraria'),
        ),
    ]
