# Generated by Django 5.0.6 on 2024-09-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url_imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='funeraria',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='funerarias', to='accounts.servicio'),
        ),
    ]
