# Generated by Django 5.0.6 on 2024-09-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_servicio_funeraria_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='funeraria',
            name='phonefijo',
            field=models.CharField(blank=True, default='Sin número', max_length=14, null=True),
        ),
    ]
