# Generated by Django 5.0.6 on 2024-10-01 22:00

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_funeraria_phonefijo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='url_imagen',
            field=models.ImageField(blank=True, null=True, storage=accounts.models.MediaStorage(), upload_to='servicios/'),
        ),
    ]
