# Generated by Django 5.0.6 on 2024-10-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_servicio_url_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='funeraria',
            name='tyc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
