# Generated by Django 5.0.6 on 2024-11-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_tipo_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='funcion',
            field=models.CharField(blank=True, default='Administrador', max_length=100, null=True),
        ),
    ]
