# Generated by Django 5.0.6 on 2024-08-20 19:37

import django.db.models.deletion
import vehiculos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100, null=True, unique=True)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(storage=vehiculos.models.MediaStorage(), upload_to=vehiculos.models.custom_filename_vehicles)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('funeraria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='accounts.funeraria')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehicletype')),
            ],
        ),
    ]
