# Generated by Django 5.0.6 on 2024-07-15 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('RegistrationNumber', models.CharField(max_length=100, unique=True)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehicletype')),
            ],
        ),
    ]
