# Generated by Django 5.0.6 on 2024-11-10 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='type',
        ),
    ]
