# Generated by Django 5.0.6 on 2024-11-10 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_remove_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehicletype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
