# Generated by Django 5.0.6 on 2024-09-15 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventario', '0001_initial'),
        ('vehiculos', '0001_initial'),
        ('velatorios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fallecido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('estado_civil', models.CharField(max_length=50)),
                ('domicilio', models.CharField(max_length=255)),
                ('nivel_estudios', models.CharField(blank=True, max_length=100, null=True)),
                ('profesion', models.CharField(blank=True, max_length=100, null=True)),
                ('lugar_fallecimiento', models.CharField(max_length=255)),
                ('prevision', models.CharField(max_length=50)),
                ('afp', models.CharField(blank=True, max_length=100, null=True)),
                ('inp', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('parentezco_con_fallecido', models.CharField(max_length=100)),
                ('funeraria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.funeraria')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_velatorio', models.DateTimeField()),
                ('fecha_fin_velatorio', models.DateTimeField()),
                ('comuna_origen', models.CharField(max_length=100)),
                ('comuna_destino', models.CharField(blank=True, max_length=100, null=True)),
                ('cementerio_destino', models.CharField(max_length=255)),
                ('es_traslado', models.BooleanField(default=False)),
                ('valor_servicio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capilla', models.CharField(max_length=255)),
                ('tipo_pago', models.CharField(max_length=100)),
                ('condiciones_pago', models.TextField()),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('no_pagado', 'No Pagado')], max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.cliente')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.product')),
                ('sala_velatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='velatorios.salavelatorio')),
                ('trabajadores', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('vehiculos', models.ManyToManyField(to='vehiculos.vehicle')),
                ('fallecido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.fallecido')),
            ],
        ),
    ]
