# Generated by Django 5.0.6 on 2024-09-20 19:51

import contratos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_contrato_funeraria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallecido',
            name='certificado_autorizacion_sepultacion',
            field=models.FileField(blank=True, null=True, storage=contratos.models.MediaStorage(), upload_to=contratos.models.custom_filename_fallecido),
        ),
        migrations.AddField(
            model_name='fallecido',
            name='certificado_defuncion',
            field=models.FileField(blank=True, null=True, storage=contratos.models.MediaStorage(), upload_to=contratos.models.custom_filename_fallecido),
        ),
        migrations.AddField(
            model_name='fallecido',
            name='copia_cedula_identidad',
            field=models.FileField(blank=True, null=True, storage=contratos.models.MediaStorage(), upload_to=contratos.models.custom_filename_fallecido),
        ),
        migrations.AddField(
            model_name='fallecido',
            name='otros_documentos',
            field=models.FileField(blank=True, null=True, storage=contratos.models.MediaStorage(), upload_to=contratos.models.custom_filename_fallecido),
        ),
    ]
