# Generated by Django 5.0.6 on 2024-10-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='comentario',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
