# Generated by Django 5.0.6 on 2024-10-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_alter_cotizacion_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
