# Generated by Django 5.0.6 on 2024-10-08 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0009_cotizacion_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='comentario',
            new_name='comentario_interno',
        ),
    ]
