# Generated by Django 5.0.6 on 2024-10-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_rename_comentario_cotizacion_comentario_interno'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tyc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
