# Generated by Django 5.0.6 on 2024-10-20 00:25

import contratos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_funeraria_tyc'),
        ('contratos', '0011_cliente_tyc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhumacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorizado_por_mausoleo', models.FileField(blank=True, null=True, storage=contratos.models.MediaStorage(), upload_to='exhumaciones/')),
                ('declaracion_jurada_notarial', models.FileField(storage=contratos.models.MediaStorage(), upload_to='exhumaciones/')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_exhumacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('programado', 'Programado'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=50)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('verificar_retiro_ornamentos', models.BooleanField(default=False)),
                ('servicio_adicional_ornamentos', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.cliente')),
                ('fallecido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.fallecido')),
                ('funeraria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.funeraria')),
            ],
        ),
    ]
