# Generated by Django 5.0.6 on 2024-10-20 21:36

import contratos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0014_exhumacion_contrato_firmado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhumacion',
            name='contrato_firmado',
            field=models.FileField(blank=True, null=True, storage=contratos.models.MediaStorage(), upload_to='exhumaciones/'),
        ),
    ]
