# Generated by Django 5.0.6 on 2024-11-03 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0015_alter_exhumacion_contrato_firmado'),
        ('velatorios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='sala_velatorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='velatorios.salavelatorio'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='trabajadores',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
